#version 430
layout(local_size_x = 32, local_size_y = 32) in;

uniform ivec2 texSize;
uniform ivec2 spotPos;
uniform vec3 color;
uniform float intensity;

layout(rgba32f, binding = 0) uniform image2D field;

void main()
{
  ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
  vec2 p = vec2(pixelCoords - spotPos);

  vec3 splat = intensity * exp(- dot(p, p) / 200.0f) * color;
  vec3 baseD = imageLoad(field, pixelCoords).xyz;

  imageStore(field, pixelCoords, vec4(baseD + splat, 1.0f));
}
